### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by Bryceclark56** [teohrt/grePy#1]
I tried to run it, but it gave me this error???

> PS C:\Users\runes\documents> python .\README.md                                                                           > File ".\README.md", line 2
>    It's grep. Just a little slower and a little simpler
                                                       ^
> SyntaxError: EOL while scanning string literal

**Comment by teohrt** [comment]
Haha sorry man.

I'm actually developing it as we speak.

Literally seconds away from pushing out working code.

I'll get a useful readme underway momentarily as well.

You're quick!

*Trace Ohrt*
Apple | Application Developer
Code for America | Leadership Team
Iowa State University | B.S. MIS & Computer Science
teohrt18@gmail.com
641-691-3243
